[package]
name = "ddd_specification_example_lib"
version = "0.1.0"
authors = ["Damian Dziaduch <damian@dziaduch.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
